TOPDIR ?= ../..
include $(TOPDIR)/.config

$(ADC_SUPPORT)_ECMD_SRC += hardware/adc/adc.c

$(HR20_TEMP_SUPPORT)_SRC += hardware/adc/hr20-temp.c
$(HR20_TEMP_SUPPORT)_ECMD_SRC += hardware/adc/hr20-temp-ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
